services:
  app:
    build: .
    ports:
      - "8080:8000"
    volumes:
      - .:/usr/src/blog
    depends_on:
      - db
      - db_test

  db:
    image: postgres:16.3-alpine
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
      POSTGRES_DB: $DB_NAME
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  db_test:
    image: postgres:16.3-alpine
    environment:
      POSTGRES_USER: $TEST_DB_USER
      POSTGRES_PASSWORD: $TEST_DB_PASS
      POSTGRES_DB: $TEST_DB_NAME
    ports:
      - "5433:5432"
    volumes:
      - db_test_data:/var/lib/postgresql/data

volumes:
  db_data:
  db_test_data:
